# Generated by Django 5.2.7 on 2025-11-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, help_text='Your current address', max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications'),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='resume',
            name='interests',
            field=models.TextField(blank=True, help_text='Personal interests and hobbies'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, help_text='Languages you speak (e.g., English: Native, Spanish: Intermediate)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Portfolio website URL'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, help_text='Notable projects or achievements'),
        ),
        migrations.AddField(
            model_name='resume',
            name='references',
            field=models.TextField(blank=True, help_text='Professional references'),
        ),
    ]
